// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOhaYFM9C-LuHsWOXm73KSvGDizPjgur4',
    appId: '1:238090080036:web:6be0b3cb639825589e2db1',
    messagingSenderId: '238090080036',
    projectId: 'financial-freedom-2022',
    authDomain: 'financial-freedom-2022.firebaseapp.com',
    storageBucket: 'financial-freedom-2022.appspot.com',
    measurementId: 'G-YXBBGCE15N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv_xmelFiB5qPfKF4v9OGWNKco9Db0zaA',
    appId: '1:238090080036:android:0d1aaf6c2b928a839e2db1',
    messagingSenderId: '238090080036',
    projectId: 'financial-freedom-2022',
    storageBucket: 'financial-freedom-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLNDxwqauJyGaFk9mvJd7i3A0LxXvmhow',
    appId: '1:238090080036:ios:925be5ff288611239e2db1',
    messagingSenderId: '238090080036',
    projectId: 'financial-freedom-2022',
    storageBucket: 'financial-freedom-2022.appspot.com',
    iosClientId: '238090080036-i36q2vpbu76qi1pa6cgr2r42n80v2ffd.apps.googleusercontent.com',
    iosBundleId: 'com.khaidam.financialFreedom',
  );
}
